# Generated by Django 3.0.2 on 2020-01-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.TextField(choices=[('hard', 'hard'), ('medium', 'ere'), ('easy', 'rere')], default='easy'),
            preserve_default=False,
        ),
    ]
