# Generated by Django 3.0.2 on 2020-01-14 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='score_date',
        ),
        migrations.AddField(
            model_name='score',
            name='id_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
